export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'

export const GET_TODOS = 'GET_TODOS'
export const GET_TODOS_REQUEST = 'GET_TODOS_REQUEST'
export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS'
export const GET_TODOS_FAILURE = 'GET_TODOS_FAILURE'

export const CREATE_TODO = 'CREATE_TODO'
export const CREATE_TODO_REQUEST = 'CREATE_TODO_REQUEST'
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS'
export const CREATE_TODO_FAILURE = 'CREATE_TODO_FAILURE'

export const DELETE_TODO = 'DELETE_TODO'
export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST'
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS'
export const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE'

export const TOGGLE_TODO = 'TOGGLE_TODO'
export const TOGGLE_TODO_REQUEST = 'TOGGLE_TODO_REQUEST'
export const TOGGLE_TODO_SUCCESS = 'TOGGLE_TODO_SUCCESS'
export const TOGGLE_TODO_FAILURE = 'TOGGLE_TODO_FAILURE'

export const SIGNIN = 'SIGNIN'
export const SIGNIN_REQUEST = 'SIGNIN_REQUEST'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE'

export const SIGNUP = 'SIGNUP'
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const SIGNOUT = 'SIGNOUT'
export const CLEAR_AUTH_ERRORS = 'CLEAR_AUTH_ERRORS'
